export const authConstants = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    // logout
    LOGOUT: 'LOGOUT',
    // confirm password
    CONFIRM_PASSWORD_REQUEST: 'CONFIRM_PASSWORD_REQUEST',
    CONFIRM_PASSWORD_SUCCESS: 'CONFIRM_PASSWORD_SUCCESS',
    CONFIRM_PASSWORD_FAILURE: 'CONFIRM_PASSWORD_FAILURE',
    // forgot password
    FORGOT_PASSWORD_REQUEST: 'FORGOT_PASSWORD_REQUEST',
    FORGOT_PASSWORD_SUCCESS: 'FORGOT_PASSWORD_SUCCESS',
    FORGOT_PASSWORD_FAILURE: 'FORGOT_PASSWORD_FAILURE',
    // reset password
    RESET_PASSWORD_REQUEST: 'RESET_PASSWORD_REQUEST',
    RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
    RESET_PASSWORD_FAILURE: 'RESET_PASSWORD_FAILURE',
    // reset email
    RESET_EMAIL_REQUEST: 'RESET_EMAIL_REQUEST',
    RESET_EMAIL_SUCCESS: 'RESET_EMAIL_SUCCESS',
    RESET_EMAIL_FAILURE: 'RESET_EMAIL_FAILURE',
    // refresh token
    REFRESH_TOKEN_REQUEST: 'REFRESH_TOKEN_REQUEST',
    REFRESH_TOKEN_SUCCESS: 'REFRESH_TOKEN_SUCCESS',
    REFRESH_TOKEN_FAILURE: 'REFRESH_TOKEN_FAILURE',

    CHALLENGE_PASSWORD_REQUEST: 'CHALLENGE_PASSWORD_REQUEST',
    CHALLENGE_PASSWORD_SUCCESS: 'CHALLENGE_PASSWORD_SUCCESS',
    CHALLENGE_PASSWORD_FAILURE: 'CHALLENGE_PASSWORD_FAILURE',

    CAROUSEL_IMAGES_REQUEST: 'CAROUSEL_IMAGES_REQUEST',
    CAROUSEL_IMAGES_SUCCESS: 'CAROUSEL_IMAGES_SUCCESS',
    CAROUSEL_IMAGES_FAILURE: 'CAROUSEL_IMAGES_FAILURE'
};
